config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#index"
  resources :plans
  get '/todo', to: 'plans#todo'
  get '/today_calendar/:date', to: 'plans#daily'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  def after_sign_in_path_for(resource) 
      plans_path
  end
end

app/models/color.rb
class Color < ActiveHash::Base
  self.data = [
    { id: 1, name: '白', value: 'color1', code: '#fffff9'},
    { id: 2, name: '黄', value: 'color2', code: '#ffffdb' },
    { id: 3, name: '橙', value: 'color3', code: '#f7e2b9' },
    { id: 4, name: '緑', value: 'color4', code: '#e9f8d1' },
    { id: 5, name: '青', value: 'color5', code: '#daf6f9' },
    { id: 6, name: '紫', value: 'color6', code: '#f2ecff' },
    { id: 7, name: '桃', value: 'color7', code: '#fff4ff' },
    { id: 8, name: '赤', value: 'color8', code: '#ff6b6b' },
    { id: 9, name: '茶', value: 'color9', code: '#cca6ac' },
    { id: 10, name: '鼠', value: 'color10', code: '#efefef' }
  ]

  def self.options
    data.map { |color| [color[:name], color[:value]] }
  end

  def self.code(value)
    color = find_by(value: value)
    color ? color[:code] : nil
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
  serialize :notification, Array
  belongs_to :user

  self.default_timezone = :local # or 'Asia/Tokyo'

  validates :title,              presence: true
  validates :schedule_date,      presence: true
  validates :schedule_time,      presence: true
  validates :color_id,           presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :plans

  validates :name, presence: true
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Include both letters and numbers'

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    plans_path # 新規登録後リダイレクト
  end

  def after_sign_in_path_for(resource)
    plans_path # ログイン後リダイレクト
  end
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :email, :encrypted_password, :name, :profile, :occupation, :position])
  end
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
    username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
  end
end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  before_action :set_beginning_of_week

  def index
    @plans = Plan.all
    @view = params[:view]
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      redirect_to plans_path, notice: "予定が登録されました。"
    else
      puts @plan.errors.full_messages
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @plan.update(plan_params)
      redirect_to @plan, notice: "更新されました。"
    else
      render :edit
    end
  end

  def destroy
    @plan.destroy
    redirect_to plans_path, notice: "削除されました。"
  end

  def todo
    @today_plans = Plan.where(schedule_date: Date.today)
  end

  private

  def set_beginning_of_week
    Date.beginning_of_week = :sunday
  end

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def plan_params
    params.require(:plan).permit(:title, :schedule_date, :schedule_time, :color_id, :memo).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PawDo -TODOアプリ-</title>
  <%= stylesheet_link_tag 'home', media: 'all'%>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cherry+Bomb+One&family=Open+Sans:wght@300&display=swap" rel="stylesheet">
</head>
<body>
  <div class="top-page">
    <h1 class="logo"><%= image_tag "nikukyu1.png",:width => '70', :height => '70' %>PawDo<%= image_tag "nikukyu1.png",:width => '70', :height => '70' %></h1>
    <div class="button-wrap">
    <%= link_to 'ログイン', new_user_session_path, class: "button" %>
    <%= link_to '新規登録', new_user_registration_path, class: "button" %>
    </div>
    <div class="concept">
      <h2>PawDoについて</h2>
      <p>PawDoは、ねこの足跡デザインのTODOアプリです。</p>
      <p>ねこの足跡を辿りながら、日々の予定を管理しましょう！</p>
      <p>まずはアカウント作成をお願いします。</p>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pawdo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
     <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/_calendar.html.erb
<% if @view == "month" %>
  <%= render "month_calendar" %>
<% elsif @view == "week" %>
  <%= render "week_calendar" %>
<% elsif @view == "today" %>
  <%= render "today_calendar" %>
<% else %>
  <%= render "main_bar" %>
<% end %>

app/views/plans/_edit.html.erb
<%= form_with model: @plan, url: plan_path(@plan) do |form| %>
  <div class="form-max">
    <div class="form-group">
    <h1>予定修正</h1>
      <p>予定入力:</p>
      <%= form.text_field :title, required: true %>
    </div>

    <div class="form-group">
      <p>日時:</p>
       <%= form.date_field :schedule_date, value: @plan.schedule_date.to_date, required: true %>
      <%= form.time_field :schedule_time, value: @plan.schedule_time, required: true %>
    </div>

     <div class="form-group">
      <p>付箋カラー:</p>
      <div class="color-options">
        <% Color.options.each do |name, value| %>
          <p>
            <%= form.radio_button :color_id, value, checked: value == @plan.color_id %>
            <span class="color <%= value %>"></span>
          </p>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <p>予定詳細メモ:</p>
      <%= form.text_area :memo %>
    </div>
  </div>

  <div class="form-group">
    <%= form.submit "更新", class: "button" %>
  </div>
<% end %>

app/views/plans/_form.html.erb
<%= form_with model: @plan, url: plans_path do |form| %>
  <div class="form-max">
    <div class="form-group">
    <h1>予定登録</h1>
      <p>予定タイトル:</p>
      <%= form.text_field :title, required: true %>
    </div>

    <div class="form-group">
      <p>日時:</p>
      <%= form.date_field :schedule_date, value: Date.today, required: true %>
      <%= form.time_field :schedule_time, value: Time.now, required: true %>
    </div>

    <div class="form-group">
      <p>付箋カラー:</p>
      <div class="color-options">
        <% Color.options.each do |name, value| %>
          <p>
            <%= form.radio_button :color_id, value, checked: value == 'color1' %>
            <span class="color <%= value %>"></span>
          </p>
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <p>予定詳細メモ:</p>
      <%= form.text_area :memo %>
    </div>
  </div>

  <div class="form-group">
    <%= form.submit "登録", class: "button" %>
  </div>
<% end %>

app/views/plans/_main_bar.html.erb
  <div class="howto">
  <br><br><br><br>
  <h4><%= image_tag "nikukyu1.png",:width => '30', :height => '30' %>　PawDo使い方　<%= image_tag "nikukyu1.png",:width => '30', :height => '30' %></h4>
    <p>1. 予定作成リンクより入力フォームへご登録ください</p>
    <p>2. 各種カレンダーを選択して内容を確認できます</p>
    <p>3. TODOリンクをクリックすると本日のTODOが別タブで表示されます</p>
    <p>4. TODOページでは予定時間になりますと付箋が点滅します</p>
  </div>

app/views/plans/_main_header.html.erb
<div class="main">
  <div class="header">
    <a href="/plans" class="logo"><%= image_tag "nikukyu1.png",:width => '30', :height => '30' %>PawDo<%= image_tag "nikukyu1.png",:width => '30', :height => '30' %></a>
  </div>
  <div class="list">
    <ul>
      <li><%= link_to '予定作成', new_plan_path, remote: true, id: 'create-plan-link', class: "button2" %></li>
      <li><%= link_to "TODO  ", todo_path, target: "_blank", class: "button2"  %><%= image_tag "popwindow.jpg",:width => '14', :height => '14' %></li>
    </ul>
  </div>
  <div class="calendar">
    <ul>
      <li><%= link_to "今日", plans_path(view: "today"), class: "button2"  %></li>
      <li><%= link_to "今週", plans_path(view: "week"), class: "button2"  %></li>
      <li><%= link_to "今月", plans_path(view: "month"), class: "button2"  %></li>
    </ul>
  </div>
  <div class="logout">
    <% if user_signed_in? %>
      <%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: "button" %>
    <% end %>
  </div>
</div>

app/views/plans/_month_calendar.html.erb
<%= month_calendar(attribute: :schedule_date, events: @plans) do |date, plans| %>
  <%= date.day %>

<% plans_in_day = @plans.select { |plan| plan.schedule_date.to_date == date.to_date }.sort_by(&:schedule_time) %>
  <% if plans.present? %>
    
   <% plans_in_day.each do |plan| %>
      <div class="plan-title2">
        <%= image_tag "nikukyu3.png", class: "paw-image" %>
        <%= link_to "#{plan.title}", plan_path(plan) %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/plans/_show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>予定詳細</title>
  <%= stylesheet_link_tag 'show', media: 'all'%>
</head>
<body>
  <div class="container">
    <h1>予定詳細</h1>

    <div class="form-max">
      <div class="form-group">
      <div class="plan-info">
        <p class="input-label">予定:</p>
        </div>
        <div class="plan-info">
        <p class="plan-title"><%= @plan.title %></p>
      </div>
      </div>

      <div class="form-group">
      <div class="plan-info">
        <p class="input-label">日付:</p>
        </div>
        <div class="plan-info">
        <p class="plan-title"><%= DateTime.parse(@plan.schedule_date).strftime("%Y年%-m月%-d日 (%a)") %></p>
      </div>
      </div>

      <div class="form-group">
      <div class="plan-info">
        <p class="input-label">時間:</p>
        </div>
        <div class="plan-info">
        <p class="plan-title"><%= DateTime.parse(@plan.schedule_time).strftime("%H:%M") %></p>
      </div>
      </div>

  <div class="form-group">
  <div class="plan-info">
  <p class="input-label">付箋カラー:</p>
  </div>
  <div class="plan-info">
  <div class="color-sample" style="background-color: <%= Color.code(@plan.color_id) %>;"></div>
</div>
</div>

<br>


      <div class="form-group">
      <div class="plan-info">
        <p class="input-label">予定詳細メモ:</p>
        </div>
        <div class="plan-info">
        <p class="plan-title"><%= @plan.memo %></p>
      </div>
    </div>
  </div>
  <div class="form-button">
  <%= link_to "修正", edit_plan_path(@plan), class: "button" %>
  <%= link_to "削除", plan_path(@plan), data: {turbo_method: :delete, turbo_confirm: "削除しますか？"}, class: "button", id: "delete-button"%>
</div>
</body>
</html>

app/views/plans/_today_calendar.html.erb
<% Time.use_zone('Tokyo') do %>
  <%= calendar(number_of_days: 1) do |date, plans| %>
    <%= date.day %>

    <% plans_in_day = @plans.select { |plan| plan.schedule_date.to_date == date.to_date }.sort_by(&:schedule_time) %>

    <% if plans_in_day.present? %>
      <% plans_in_day.each do |plan| %>
        <div class="plan-title2">
          <%= image_tag "nikukyu3.png", class: "paw-image" %>
          <%= link_to "#{plan.schedule_time.in_time_zone.strftime('%H:%M')} #{plan.title}", plan_path(plan) %>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/plans/_week_calendar.html.erb
<%= week_calendar do |date, plans| %>
  <%= date.day %>

   <% plans_in_day = @plans.select { |plan| plan.schedule_date.to_date == date.to_date }.sort_by(&:schedule_time) %>

  <% if plans_in_day.present? %>
    
    <% plans_in_day.each do |plan| %>
      <div class="plan-title2">
      <%= image_tag "nikukyu3.png", class: "paw-image" %>
        <%= link_to "#{plan.schedule_time} #{plan.title}", plan_path(plan) %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/plans/edit.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PawDo</title>
<%= stylesheet_link_tag 'plan', media: 'all'%>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cherry+Bomb+One&family=Open+Sans:wght@300&display=swap" rel="stylesheet">
</head>
<body>
<header>
        <div class = "cont">
    <div class = "left-cont">
      <%= render "main_header" %>
      </div>
      <div class = "right-cont">
      <%= render 'edit' %>
    </div>
</div>
</header>
</body>
</html>

app/views/plans/index.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PawDo</title>
<%= stylesheet_link_tag 'plan', media: 'all'%>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cherry+Bomb+One&family=Open+Sans:wght@300&display=swap" rel="stylesheet">
</head>
<body>
<header>
    <div class = "cont">
    <div class = "left-cont">
      <%= render "main_header" %>
      </div>
      <div class = "right-cont">
      <%= render "calendar" %>
    </div>
    </div>
</header>
</body>
</html>

app/views/plans/new.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PawDo</title>
<%= stylesheet_link_tag 'plan', media: 'all'%>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cherry+Bomb+One&family=Open+Sans:wght@300&display=swap" rel="stylesheet">
</head>
<body>
<header>
        <div class = "cont">
    <div class = "left-cont">
      <%= render "main_header" %>
      </div>
      <div class = "right-cont">
      <%= render 'form' %>
    </div>
</div>
</header>
</body>
</html>

app/views/plans/show.html.erb
<!DOCTYPE html>
<html>
<head>
<title>PawDo</title>
<%= stylesheet_link_tag 'plan', media: 'all'%>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Cherry+Bomb+One&family=Open+Sans:wght@300&display=swap" rel="stylesheet">
</head>
<body>
<header>
       <div class = "cont">
    <div class = "left-cont">
      <%= render "main_header" %>
      </div>
      <div class = "right-cont">
      <%= render 'show' %>
    </div>
</div>
</header>
</body>
</html>

app/views/plans/todo.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TODO一覧</title>

  <style>
  h1 {
      text-align: left;
      margin-bottom: 10px;
    }
    p {
      margin: 10px 0 0 20px;
    }
    /* 付箋のスタイル */
    .sticky-note {
      display: none;
      width: 200px;
      padding: 20px;
      margin: 15px;
      border: 1px solid #000000;
      position: relative;
    }

    /* 完了マークのスタイル */
     .completed-mark {
      position: absolute;
      top: 13px;
      right: 5px;
      /* 以下の行を追加して肉球の画像を設定 */
      background-image: url(<%= asset_path("nikukyu3.png") %>);
      width: 30px;
      height: 30px;
      background-size: contain;
      background-repeat: no-repeat;
      cursor: pointer;
    }

    /* タイトルと日時のスタイル */
    .title {
      font-weight: bold;
    }

    .datetime {
      margin-top: 5px;
      color: #666;
    }

    .nowtime{
      padding: 20px 0;
      font-size: 18px;

    }

      @keyframes blink {
      0% { opacity: 1; }
      50% { opacity: 0; }
      100% { opacity: 1; }
    }

    .blinking {
      animation: blink 1s infinite; 
  </style>

</head>
<body>
  <h1>TODO一覧</h1>
  <p>完了したら肉球をクリックで削除</p>
  <p>ページを更新すると予定が一覧に戻ります</p>
  <div class="nowtime">
  <p>現在時刻：</p>
  <p id="current-time"></p>
  </div>
 <div id="todo-list">
    <% @today_plans.sort_by { |plan| [plan.schedule_date, plan.schedule_time] }.each do |plan| %>
      <div class="sticky-note" data-schedule-date="<%= plan.schedule_date %>" data-schedule-time="<%= plan.schedule_time %>" style="background-color: <%= Color.code(plan.color_id) %>;">
        <div class="completed-mark"></div>
        <div class="title"><%= plan.schedule_time %>　<%= plan.title %></div>
      </div>
    <% end %>
    </div>

  <script>
     // 曜日の日本語表記を取得する関数
    function getJapaneseDayOfWeek(dayOfWeek) {
      const days = ["日", "月", "火", "水", "木", "金", "土"];
      return days[dayOfWeek];
    }

   // 現在の日時を表示する関数
    function showCurrentTime() {
      const now = new Date();
      const options = {
        timeZone: 'Asia/Tokyo', // 日本のタイムゾーン
        year: 'numeric',
        month: 'numeric',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        weekday: 'short'
      };
      const formattedDateTime = new Intl.DateTimeFormat('ja-JP', options).format(now);
      document.getElementById('current-time').textContent = formattedDateTime;
    }

    // 1秒ごとに現在の日時を更新するためのタイマー
    setInterval(showCurrentTime, 1000);
    
    window.addEventListener('load', () => {
    startIntervalForBlinking();
  
    const deletedNotes = JSON.parse(localStorage.getItem('deletedNotes')) || [];
  
    const pawMarks = document.querySelectorAll('.completed-mark');
    pawMarks.forEach((pawMark) => {
      const stickyNote = pawMark.closest('.sticky-note');
      const scheduleDate = stickyNote.dataset.scheduleDate;
      const scheduleTime = stickyNote.dataset.scheduleTime;
  
      if (deletedNotes.some(note => note.scheduleDate === scheduleDate && note.scheduleTime === scheduleTime)) {
        stickyNote.style.display = 'none';
      } else {
        stickyNote.style.display = 'block';
      }
  
      pawMark.addEventListener('click', deleteStickyNote);
    });
  });

// 予定の時間が来たかを確認して、付箋を点滅させる関数
function checkAndBlinkStickyNotes() {
  const stickyNotes = document.querySelectorAll('.sticky-note');
  stickyNotes.forEach((note) => {
    const scheduleDate = note.dataset.scheduleDate;
    const scheduleTime = note.dataset.scheduleTime;
    const scheduleDateTime = new Date(`${scheduleDate} ${scheduleTime}`);

    if (Date.now() >= scheduleDateTime) {
      note.classList.add('blinking');
    } else {
      note.classList.remove('blinking');
    }
  });
}

// 付箋を削除するための関数
function deleteStickyNote() {
  const confirmation = confirm("この付箋を削除しますか？");
  if (confirmation) {
    const stickyNote = this.closest('.sticky-note');
    const scheduleDate = stickyNote.dataset.scheduleDate;
    const scheduleTime = stickyNote.dataset.scheduleTime;

    // 削除した付箋の情報をローカルストレージに保存
    const deletedNotes = JSON.parse(localStorage.getItem('deletedNotes')) || [];
    deletedNotes.push({ scheduleDate, scheduleTime });
    localStorage.setItem('deletedNotes', JSON.stringify(deletedNotes));

    stickyNote.remove();
  }
}

// ページロード時に呼び出される関数
window.addEventListener('load', () => {
  startIntervalForBlinking();

  const deletedNotes = JSON.parse(localStorage.getItem('deletedNotes')) || [];

  const pawMarks = document.querySelectorAll('.completed-mark');
  pawMarks.forEach((pawMark) => {
    const stickyNote = pawMark.closest('.sticky-note');
    const scheduleDate = stickyNote.dataset.scheduleDate;
    const scheduleTime = stickyNote.dataset.scheduleTime;

    // 削除した付箋の情報がローカルストレージにある場合は非表示にする
    if (deletedNotes.some(note => note.scheduleDate === scheduleDate && note.scheduleTime === scheduleTime)) {
      stickyNote.style.display = 'none';
    } else {
      stickyNote.style.display = 'block';
    }

    pawMark.addEventListener('click', deleteStickyNote);
  });
});

// 定期的に付箋を点滅させるための関数
function startIntervalForBlinking() {
  checkAndBlinkStickyNotes();
  setInterval(checkAndBlinkStickyNotes, 1000); // 1秒ごとに点滅を確認
}

// イベントリスナーを追加し、ページロード時に必要な関数を呼び出す
window.addEventListener('load', () => {
  startIntervalForBlinking();

  const pawMarks = document.querySelectorAll('.completed-mark');
  pawMarks.forEach((pawMark) => {
    pawMark.addEventListener('click', deleteStickyNote);
  });
});
  </script>
</body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>